package com.model;

/**
 * TAdmin generated by MyEclipse Persistence Tools
 */

public class Ks implements java.io.Serializable {

	// Fields

	private Integer id;

	private String names;//用户名


	// Constructors

	/** default constructor */
	public Ks() {
	}


	public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}

	public String getNames() {
		return names;
	}


	public void setNames(String names) {
		this.names = names;
	}

}